// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynvnzmkpifwteyuxondc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inludm56bWtwaWZ3dGV5dXhvbmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MzM0ODksImV4cCI6MjA1NjAwOTQ4OX0.-7uEZS3Ra22P3KqWgVn1JVgzWlTOxgKnYnjiykgWpms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);