require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorBackgroundRunner', :path => '../../node_modules/@capacitor/background-runner'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Fix CapacitorCordova header inclusion issues
  installer.pods_project.targets.each do |target|
    if target.name == 'CapacitorCordova'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_WARN_DOUBLE_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
  end
  
  # Fix for all pods to ensure compatibility
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  
  # Fix XCFrameworks copy script phase warning by adding output files
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |build_phase|
      if build_phase.respond_to?(:name) && build_phase.name == '[CP] Copy XCFrameworks'
        # Add output files to prevent the warning
        if build_phase.respond_to?(:output_paths)
          build_phase.output_paths ||= []
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Capacitor.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorCordova.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorBackgroundRunner.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorBrowser.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorCamera.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorGeolocation.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/CapacitorSplashScreen.framework'
          build_phase.output_paths << '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/RevenuecatPurchasesCapacitor.framework'
        end
      end
    end
  end
end
